openapi: 3.2.0
info:
  title: Hetzner Cloud Placement Groups API
  version: 1.0.0
  x-summary: 'Manage Hetzner Cloud services and resources linked to them, such as Floating IPs, Volumes and Load Balancers.

    '
  description: '# Overview


    This is the official documentation for the Hetzner Cloud API.'
servers:
- url: https://api.hetzner.cloud/v1
security:
- APIToken: []
tags:
- name: Placement Groups
  description: Placement groups are used to influence the location of interdependent virtual servers in our data centers.
paths:
  /placement_groups:
    get:
      operationId: list_placement_groups
      summary: List Placement Groups
      description: Returns all Placement Group objects.
      tags:
      - Placement Groups
      parameters:
      - description: 'Sort resources by field and direction. May be used multiple times.


          For more information, see "[Sorting](#description/sorting)".

          '
        name: sort
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - id
            - id:asc
            - id:desc
            - name
            - name:asc
            - name:desc
            - created
            - created:asc
            - created:desc
      - description: 'Filter resources by their name.


          The response will only contain the resources

          matching exactly the specified name.

          '
        name: name
        in: query
        required: false
        schema:
          type: string
      - description: 'Filter resources by labels.


          The response will only contain resources matching the label selector.

          For more information, see "[Label Selector](#description/label-selector)".

          '
        name: label_selector
        in: query
        required: false
        schema:
          type: string
      - description: 'Filter resources by type. May be used multiple times.


          The response will only contain the resources with the specified type.

          '
        name: type
        in: query
        required: false
        schema:
          type: array
          items:
            description: 'Type of Placement Group.

              '
            type: string
            enum:
            - spread
            example: spread
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: PlacementGroupsResponse
                type: object
                properties:
                  placement_groups:
                    type: array
                    items:
                      title: PlacementGroup
                      type: object
                      properties:
                        id:
                          description: ID of the [Placement Group](#tag/placement-groups).
                          type: integer
                          format: int64
                          minimum: 1
                          maximum: 9007199254740991
                          example: 42
                        name:
                          description: Name of the Resource. Must be unique per Project.
                          type: string
                          example: my-resource
                        labels:
                          description: 'User-defined labels (`key/value` pairs) for the Resource.

                            For more information, see "[Labels](#description/labels)".

                            '
                          type: object
                          additionalProperties:
                            type: string
                          example:
                            environment: prod
                            example.com/my: label
                            just-a-key: ''
                        type:
                          description: 'Type of Placement Group.

                            '
                          type: string
                          enum:
                          - spread
                          example: spread
                        created:
                          description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type: string
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                        servers:
                          description: Array of IDs of Servers that are part of this Placement Group.
                          type: array
                          items:
                            type: integer
                            format: int64
                          example:
                          - 42
                      required:
                      - id
                      - name
                      - labels
                      - type
                      - created
                      - servers
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - placement_groups
                - meta
              examples:
                default:
                  value:
                    placement_groups:
                    - id: 897
                      name: my Placement Group
                      labels:
                        key: value
                      type: spread
                      created: '2019-01-08T12:10:00Z'
                      servers:
                      - 4711
                      - 4712
                    meta:
                      pagination:
                        page: 1
                        per_page: 25
                        previous_page: null
                        next_page: null
                        last_page: 1
                        total_entries: 21
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tplacementGroups, err := client.PlacementGroup.All(ctx)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          placement_groups = client.placement_groups.get_all()'
      - lang: Shell
        label: CLI
        source: hcloud placement-group list
    post:
      operationId: create_placement_group
      summary: Create a PlacementGroup
      description: Creates a new Placement Group.
      tags:
      - Placement Groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: CreatePlacementGroupRequest
              type: object
              properties:
                name:
                  description: Name of the Placement Group.
                  type: string
                  example: my Placement Group
                labels:
                  description: 'User-defined labels (`key/value` pairs) for the Resource.

                    For more information, see "[Labels](#description/labels)".

                    '
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    environment: prod
                    example.com/my: label
                    just-a-key: ''
                type:
                  description: Define the Placement Group Type.
                  type: string
                  enum:
                  - spread
                  example: spread
              required:
              - name
              - type
            examples:
              default:
                value:
                  name: my Placement Group
                  type: spread
      responses:
        '201':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: CreatePlacementGroupResponse
                type: object
                properties:
                  placement_group:
                    title: PlacementGroup
                    type: object
                    properties:
                      id:
                        description: ID of the [Placement Group](#tag/placement-groups).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      name:
                        description: Name of the Resource. Must be unique per Project.
                        type: string
                        example: my-resource
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      type:
                        description: 'Type of Placement Group.

                          '
                        type: string
                        enum:
                        - spread
                        example: spread
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      servers:
                        description: Array of IDs of Servers that are part of this Placement Group.
                        type: array
                        items:
                          type: integer
                          format: int64
                        example:
                        - 42
                    required:
                    - id
                    - name
                    - labels
                    - type
                    - created
                    - servers
                  action:
                    title: ActionNullable
                    type:
                    - object
                    - 'null'
                    properties:
                      id:
                        description: ID of the [Action](#description/actions).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      command:
                        description: Command executed in the Action.
                        type: string
                        example: start_resource
                      status:
                        description: Status of the Action.
                        type: string
                        enum:
                        - running
                        - success
                        - error
                      started:
                        description: Point in time when the Action was started (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      finished:
                        description: Point in time when the Action was finished (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format). Only set if the Action is finished otherwise null.
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      progress:
                        description: Progress of the Action in percent.
                        type: integer
                        format: int32
                        example: 100
                      resources:
                        description: Resources the Action relates to.
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              description: ID of the Resource.
                              type: integer
                              format: int64
                              minimum: 1
                              maximum: 9007199254740991
                              example: 42
                            type:
                              description: Type of the Resource.
                              type: string
                              example: server
                          required:
                          - id
                          - type
                      error:
                        description: Error message for the Action if an error occurred, otherwise null.
                        type:
                        - object
                        - 'null'
                        properties:
                          code:
                            description: Fixed error code for machines.
                            type: string
                            example: action_failed
                          message:
                            description: Error message for humans.
                            type: string
                            example: Action failed
                        required:
                        - code
                        - message
                    required:
                    - id
                    - command
                    - status
                    - progress
                    - started
                    - finished
                    - resources
                    - error
                required:
                - placement_group
              examples:
                default:
                  value:
                    placement_group:
                      id: 897
                      name: my Placement Group
                      labels:
                        key: value
                      type: spread
                      created: '2019-01-08T12:10:00Z'
                      servers: []
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tresult, _, err := client.PlacementGroup.Create(ctx, hcloud.PlacementGroupCreateOpts{\n\t\tName: \"my Placement Group\",\n\t\tType: hcloud.PlacementGroupTypeSpread,\n\t})\n\n\terr = client.Action.WaitFor(ctx, result.Action)\n\n\tplacementGroup := result.PlacementGroup\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nresponse = client.placement_groups.create(\n    name=\"my Placement Group\",\n    type=\"spread\",\n)\n\nresponse.action.wait_until_finished()\n\nplacement_group = response.placement_group"
      - lang: Shell
        label: CLI
        source: "hcloud placement-group create \\\n    --name \"my Placement Group\" \\\n    --type spread"
  /placement_groups/{id}:
    get:
      operationId: get_placement_group
      summary: Get a PlacementGroup
      description: Gets a specific Placement Group object.
      tags:
      - Placement Groups
      parameters:
      - description: ID of the Placement Group.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Placement Group](#tag/placement-groups).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: PlacementGroupResponse
                type: object
                properties:
                  placement_group:
                    title: PlacementGroup
                    type: object
                    properties:
                      id:
                        description: ID of the [Placement Group](#tag/placement-groups).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      name:
                        description: Name of the Resource. Must be unique per Project.
                        type: string
                        example: my-resource
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      type:
                        description: 'Type of Placement Group.

                          '
                        type: string
                        enum:
                        - spread
                        example: spread
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      servers:
                        description: Array of IDs of Servers that are part of this Placement Group.
                        type: array
                        items:
                          type: integer
                          format: int64
                        example:
                        - 42
                    required:
                    - id
                    - name
                    - labels
                    - type
                    - created
                    - servers
                required:
                - placement_group
              examples:
                default:
                  value:
                    placement_group:
                      id: 897
                      name: my Placement Group
                      labels:
                        key: value
                      type: spread
                      created: '2019-01-08T12:10:00Z'
                      servers:
                      - 4711
                      - 4712
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tplacementGroups, _, err := client.PlacementGroup.GetByID(ctx, 123)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          placement_group = client.placement_groups.get_by_id(123)'
      - lang: Shell
        label: CLI
        source: hcloud placement-group describe $PLACEMENTGROUP
    put:
      operationId: update_placement_group
      summary: Update a PlacementGroup
      description: 'Updates the Placement Group properties.


        Note: if the Placement Group object changes during the request, the response will be a “conflict” error.'
      tags:
      - Placement Groups
      parameters:
      - description: ID of the Placement Group.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Placement Group](#tag/placement-groups).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: UpdatePlacementGroupRequest
              type: object
              properties:
                name:
                  description: New Placement Group name.
                  type: string
                  example: my Placement Group
                labels:
                  description: 'User-defined labels (`key/value` pairs) for the Resource.


                    Note that the set of [Labels](#description/labels) provided in the request will overwrite the

                    existing one.


                    For more information, see "[Labels](#description/labels)".

                    '
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    environment: prod
                    example.com/my: label
                    just-a-key: ''
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: PlacementGroupResponse
                type: object
                properties:
                  placement_group:
                    title: PlacementGroup
                    type: object
                    properties:
                      id:
                        description: ID of the [Placement Group](#tag/placement-groups).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      name:
                        description: Name of the Resource. Must be unique per Project.
                        type: string
                        example: my-resource
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      type:
                        description: 'Type of Placement Group.

                          '
                        type: string
                        enum:
                        - spread
                        example: spread
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      servers:
                        description: Array of IDs of Servers that are part of this Placement Group.
                        type: array
                        items:
                          type: integer
                          format: int64
                        example:
                        - 42
                    required:
                    - id
                    - name
                    - labels
                    - type
                    - created
                    - servers
                required:
                - placement_group
              examples:
                default:
                  value:
                    placement_group:
                      id: 897
                      name: my Placement Group
                      labels:
                        key: value
                      type: spread
                      created: '2019-01-08T12:10:00Z'
                      servers:
                      - 4711
                      - 4712
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tplacementGroup, _, err := client.PlacementGroup.Update(ctx, &hcloud.PlacementGroup{ID: 123}, hcloud.PlacementGroupUpdateOpts{\n\t\tLabels: map[string]string{\n\t\t\t\"environment\":    \"prod\",\n\t\t\t\"example.com/my\": \"label\",\n\t\t\t\"just-a-key\":     \"\",\n\t\t},\n\t\tName: \"my Placement Group\",\n\t})\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\nfrom hcloud.placement_groups import PlacementGroup\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nplacement_group = client.placement_groups.update(\n    placement_group=PlacementGroup(id=123),\n    labels={\n        \"environment\": \"prod\",\n        \"example.com/my\": \"label\",\n        \"just-a-key\": \"\",\n    },\n    name=\"my Placement Group\",\n)"
      - lang: Shell
        label: CLI
        source: "hcloud placement-group update $PLACEMENTGROUP --name \"my Placement Group\"\nhcloud placement-group add-label --overwrite $PLACEMENTGROUP \\\n    \"environment=prod\" \"example.com/my=label\" \"just-a-key=\"\nhcloud placement-group remove-label $PLACEMENTGROUP \\\n    \"environment\" \"example.com\" \"just-a-key\""
    delete:
      operationId: delete_placement_group
      summary: Delete a PlacementGroup
      description: Deletes a Placement Group.
      tags:
      - Placement Groups
      parameters:
      - description: ID of the Placement Group.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Placement Group](#tag/placement-groups).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '204':
          description: Request succeeded.
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\t_, err := client.PlacementGroup.Delete(ctx, &hcloud.PlacementGroup{ID: 123})\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\nfrom hcloud.placement_groups import PlacementGroup\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nclient.placement_groups.delete(\n    placement_group=PlacementGroup(id=123),\n)"
      - lang: Shell
        label: CLI
        source: hcloud placement-group delete $PLACEMENTGROUP
components:
  securitySchemes:
    APIToken:
      type: http
      scheme: bearer
x-tagGroups:
- name: Actions
  tags:
  - Actions
- name: Servers
  tags:
  - Servers
  - Server Actions
  - Server Types
  - Images
  - Image Actions
  - ISOs
  - Placement Groups
  - Primary IPs
  - Primary IP Actions
- name: Volumes
  tags:
  - Volumes
  - Volume Actions
- name: Floating IPs
  tags:
  - Floating IPs
  - Floating IP Actions
- name: Firewalls
  tags:
  - Firewalls
  - Firewall Actions
- name: Load Balancers
  tags:
  - Load Balancers
  - Load Balancer Actions
  - Load Balancer Types
- name: Networks
  tags:
  - Networks
  - Network Actions
- name: DNS
  tags:
  - Zones
  - Zone Actions
  - Zone RRSets
  - Zone RRSet Actions
- name: Security
  tags:
  - Certificates
  - Certificate Actions
  - SSH Keys
- name: Locations
  tags:
  - Locations
  - Data Centers
- name: Billing
  tags:
  - Pricing
