openapi: 3.2.0
info:
  title: Hetzner Cloud Load Balancer Types API
  version: 1.0.0
  x-summary: 'Manage Hetzner Cloud services and resources linked to them, such as Floating IPs, Volumes and Load Balancers.

    '
  description: '# Overview


    This is the official documentation for the Hetzner Cloud API.'
servers:
- url: https://api.hetzner.cloud/v1
security:
- APIToken: []
tags:
- name: Load Balancer Types
  description: 'Load Balancer types define kinds of Load Balancers offered. Each type has an hourly and a monthly cost. You will pay whichever amount is lower for your usage of this specific Load Balancer. Costs may differ between Locations.


    All prices are displayed in the currency of the project owner''s account.'
paths:
  /load_balancer_types:
    get:
      operationId: list_load_balancer_types
      summary: List Load Balancer Types
      description: Gets all Load Balancer type objects.
      tags:
      - Load Balancer Types
      parameters:
      - description: 'Filter resources by their name.


          The response will only contain the resources

          matching exactly the specified name.

          '
        name: name
        in: query
        required: false
        schema:
          type: string
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  load_balancer_types:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: ID of the Load Balancer type.
                          type: integer
                          format: int64
                          example: 1
                        name:
                          description: Unique identifier of the Load Balancer type.
                          type: string
                          example: lb11
                        description:
                          description: Description of the Load Balancer type.
                          type: string
                          example: LB11
                        max_connections:
                          description: Number of maximum simultaneous open connections.
                          type: integer
                          format: int64
                          example: 20000
                        max_services:
                          description: Number of services a Load Balancer of this type can have.
                          type: integer
                          format: int64
                          example: 5
                        max_targets:
                          description: Number of targets a single Load Balancer can have.
                          type: integer
                          format: int64
                          example: 25
                        max_assigned_certificates:
                          description: Number of SSL Certificates that can be assigned to a single Load Balancer.
                          type: integer
                          format: int64
                          example: 10
                        deprecated:
                          description: Point in time when the Load Balancer type is deprecated (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type:
                          - string
                          - 'null'
                          format: date-time
                          example: '2016-01-30T23:50:00Z'
                        prices:
                          description: Price per [Location](#tag/locations).
                          type: array
                          items:
                            type: object
                            properties:
                              location:
                                description: Name of the [Location](#tag/locations) the price is for.
                                type: string
                                example: fsn1
                              price_hourly:
                                description: Hourly price in this [Location](#tag/locations).
                                type: object
                                properties:
                                  net:
                                    description: Price without VAT.
                                    type: string
                                    format: decimal
                                    example: '1.0000'
                                  gross:
                                    description: Price with VAT added.
                                    type: string
                                    format: decimal
                                    example: '1.1900'
                                required:
                                - net
                                - gross
                              price_monthly:
                                description: Monthly price in this [Location](#tag/locations).
                                type: object
                                properties:
                                  net:
                                    description: Price without VAT.
                                    type: string
                                    format: decimal
                                    example: '1.0000'
                                  gross:
                                    description: Price with VAT added.
                                    type: string
                                    format: decimal
                                    example: '1.1900'
                                required:
                                - net
                                - gross
                              included_traffic:
                                description: Free traffic per month in bytes in this [Location](#tag/locations).
                                type: integer
                                format: int64
                                example: 654321
                              price_per_tb_traffic:
                                description: Additional traffic price per TB in this [Location](#tag/locations).
                                type: object
                                properties:
                                  net:
                                    description: Price without VAT.
                                    type: string
                                    format: decimal
                                    example: '1.0000'
                                  gross:
                                    description: Price with VAT added.
                                    type: string
                                    format: decimal
                                    example: '1.1900'
                                required:
                                - net
                                - gross
                            required:
                            - location
                            - price_hourly
                            - price_monthly
                            - included_traffic
                            - price_per_tb_traffic
                      required:
                      - id
                      - name
                      - description
                      - max_connections
                      - max_services
                      - max_targets
                      - max_assigned_certificates
                      - deprecated
                      - prices
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - load_balancer_types
                - meta
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tloadBalancerTypes, err := client.LoadBalancerType.All(ctx)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          load_balancer_types = client.load_balancer_types.get_all()'
      - lang: Shell
        label: CLI
        source: hcloud load-balancer-type list
  /load_balancer_types/{id}:
    get:
      operationId: get_load_balancer_type
      summary: Get a Load Balancer Type
      description: Gets a specific Load Balancer type object.
      tags:
      - Load Balancer Types
      parameters:
      - description: ID of the Load Balancer Type.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Load Balancer Type](#tag/load-balancer-types).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  load_balancer_type:
                    type: object
                    properties:
                      id:
                        description: ID of the Load Balancer type.
                        type: integer
                        format: int64
                        example: 1
                      name:
                        description: Unique identifier of the Load Balancer type.
                        type: string
                        example: lb11
                      description:
                        description: Description of the Load Balancer type.
                        type: string
                        example: LB11
                      max_connections:
                        description: Number of maximum simultaneous open connections.
                        type: integer
                        format: int64
                        example: 20000
                      max_services:
                        description: Number of services a Load Balancer of this type can have.
                        type: integer
                        format: int64
                        example: 5
                      max_targets:
                        description: Number of targets a single Load Balancer can have.
                        type: integer
                        format: int64
                        example: 25
                      max_assigned_certificates:
                        description: Number of SSL Certificates that can be assigned to a single Load Balancer.
                        type: integer
                        format: int64
                        example: 10
                      deprecated:
                        description: Point in time when the Load Balancer type is deprecated (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2016-01-30T23:50:00Z'
                      prices:
                        description: Price per [Location](#tag/locations).
                        type: array
                        items:
                          type: object
                          properties:
                            location:
                              description: Name of the [Location](#tag/locations) the price is for.
                              type: string
                              example: fsn1
                            price_hourly:
                              description: Hourly price in this [Location](#tag/locations).
                              type: object
                              properties:
                                net:
                                  description: Price without VAT.
                                  type: string
                                  format: decimal
                                  example: '1.0000'
                                gross:
                                  description: Price with VAT added.
                                  type: string
                                  format: decimal
                                  example: '1.1900'
                              required:
                              - net
                              - gross
                            price_monthly:
                              description: Monthly price in this [Location](#tag/locations).
                              type: object
                              properties:
                                net:
                                  description: Price without VAT.
                                  type: string
                                  format: decimal
                                  example: '1.0000'
                                gross:
                                  description: Price with VAT added.
                                  type: string
                                  format: decimal
                                  example: '1.1900'
                              required:
                              - net
                              - gross
                            included_traffic:
                              description: Free traffic per month in bytes in this [Location](#tag/locations).
                              type: integer
                              format: int64
                              example: 654321
                            price_per_tb_traffic:
                              description: Additional traffic price per TB in this [Location](#tag/locations).
                              type: object
                              properties:
                                net:
                                  description: Price without VAT.
                                  type: string
                                  format: decimal
                                  example: '1.0000'
                                gross:
                                  description: Price with VAT added.
                                  type: string
                                  format: decimal
                                  example: '1.1900'
                              required:
                              - net
                              - gross
                          required:
                          - location
                          - price_hourly
                          - price_monthly
                          - included_traffic
                          - price_per_tb_traffic
                    required:
                    - id
                    - name
                    - description
                    - max_connections
                    - max_services
                    - max_targets
                    - max_assigned_certificates
                    - deprecated
                    - prices
                required:
                - load_balancer_type
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tloadBalancerType, _, err := client.LoadBalancerType.GetByID(ctx, 123)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          load_balancer_type = client.load_balancer_types.get_by_id(123)'
      - lang: Shell
        label: CLI
        source: hcloud load-balancer-type describe $LOADBALANCERTYPE
components:
  securitySchemes:
    APIToken:
      type: http
      scheme: bearer
x-tagGroups:
- name: Actions
  tags:
  - Actions
- name: Servers
  tags:
  - Servers
  - Server Actions
  - Server Types
  - Images
  - Image Actions
  - ISOs
  - Placement Groups
  - Primary IPs
  - Primary IP Actions
- name: Volumes
  tags:
  - Volumes
  - Volume Actions
- name: Floating IPs
  tags:
  - Floating IPs
  - Floating IP Actions
- name: Firewalls
  tags:
  - Firewalls
  - Firewall Actions
- name: Load Balancers
  tags:
  - Load Balancers
  - Load Balancer Actions
  - Load Balancer Types
- name: Networks
  tags:
  - Networks
  - Network Actions
- name: DNS
  tags:
  - Zones
  - Zone Actions
  - Zone RRSets
  - Zone RRSet Actions
- name: Security
  tags:
  - Certificates
  - Certificate Actions
  - SSH Keys
- name: Locations
  tags:
  - Locations
  - Data Centers
- name: Billing
  tags:
  - Pricing
