openapi: 3.2.0
info:
  title: Hetzner Cloud SSH Keys API
  version: 1.0.0
  x-summary: 'Manage Hetzner Cloud services and resources linked to them, such as Floating IPs, Volumes and Load Balancers.

    '
  description: '# Overview


    This is the official documentation for the Hetzner Cloud API.'
servers:
- url: https://api.hetzner.cloud/v1
security:
- APIToken: []
tags:
- name: SSH Keys
  description: SSH keys are public keys you provide to the cloud system. They can be injected into Servers at creation time. We highly recommend that you use keys instead of passwords to manage your Servers.
paths:
  /ssh_keys:
    get:
      operationId: list_ssh_keys
      summary: List SSH keys
      description: Returns all SSH key objects.
      tags:
      - SSH Keys
      parameters:
      - description: 'Sort resources by field and direction. May be used multiple times.


          For more information, see "[Sorting](#description/sorting)".

          '
        name: sort
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - id
            - id:asc
            - id:desc
            - name
            - name:asc
            - name:desc
      - description: 'Filter resources by their name.


          The response will only contain the resources

          matching exactly the specified name.

          '
        name: name
        in: query
        required: false
        schema:
          type: string
      - description: May be used to filter SSH keys by their fingerprint. The response will only contain the SSH key matching the specified fingerprint.
        name: fingerprint
        in: query
        required: false
        schema:
          type: string
      - description: 'Filter resources by labels.


          The response will only contain resources matching the label selector.

          For more information, see "[Label Selector](#description/label-selector)".

          '
        name: label_selector
        in: query
        required: false
        schema:
          type: string
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ssh_keys:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: ID of the [SSH Key](#tag/ssh-keys).
                          type: integer
                          format: int64
                          minimum: 1
                          maximum: 9007199254740991
                          example: 42
                        name:
                          description: Name of the Resource. Must be unique per Project.
                          type: string
                          example: my-resource
                        fingerprint:
                          description: MD5 fingerprint of the SSH public key.
                          type: string
                          example: b7:2f:30:a0:2f:6c:58:6c:21:04:58:61:ba:06:3b:2f
                        public_key:
                          description: Public key.
                          type: string
                          example: ssh-rsa AAAjjk76kgf...Xt
                        labels:
                          description: 'User-defined labels (`key/value` pairs) for the Resource.

                            For more information, see "[Labels](#description/labels)".

                            '
                          type: object
                          additionalProperties:
                            type: string
                          example:
                            environment: prod
                            example.com/my: label
                            just-a-key: ''
                        created:
                          description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type: string
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                      required:
                      - id
                      - name
                      - fingerprint
                      - public_key
                      - labels
                      - created
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - ssh_keys
                - meta
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tsshKeys, err := client.SSHKey.All(ctx)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          ssh_keys = client.ssh_keys.get_all()'
      - lang: Shell
        label: CLI
        source: hcloud ssh-key list
    post:
      operationId: create_ssh_key
      summary: Create an SSH key
      description: Creates a new SSH key with the given `name` and `public_key`. Once an SSH key is created, it can be used in other calls such as creating Servers.
      tags:
      - SSH Keys
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Name of the SSH key.
                  type: string
                  example: My ssh key
                public_key:
                  description: Public key.
                  type: string
                  example: ssh-rsa AAAjjk76kgf...Xt
                labels:
                  description: 'User-defined labels (`key/value` pairs) for the Resource.

                    For more information, see "[Labels](#description/labels)".

                    '
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    environment: prod
                    example.com/my: label
                    just-a-key: ''
              required:
              - name
              - public_key
      responses:
        '201':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ssh_key:
                    type: object
                    properties:
                      id:
                        description: ID of the [SSH Key](#tag/ssh-keys).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      name:
                        description: Name of the Resource. Must be unique per Project.
                        type: string
                        example: my-resource
                      fingerprint:
                        description: MD5 fingerprint of the SSH public key.
                        type: string
                        example: b7:2f:30:a0:2f:6c:58:6c:21:04:58:61:ba:06:3b:2f
                      public_key:
                        description: Public key.
                        type: string
                        example: ssh-rsa AAAjjk76kgf...Xt
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                    required:
                    - id
                    - name
                    - fingerprint
                    - public_key
                    - labels
                    - created
                required:
                - ssh_key
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tsshKey, _, err := client.SSHKey.Create(ctx, hcloud.SSHKeyCreateOpts{\n\t\tLabels: map[string]string{\n\t\t\t\"environment\":    \"prod\",\n\t\t\t\"example.com/my\": \"label\",\n\t\t\t\"just-a-key\":     \"\",\n\t\t},\n\t\tName:      \"My ssh key\",\n\t\tPublicKey: \"ssh-rsa AAAjjk76kgf...Xt\",\n\t})\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nssh_key = client.ssh_keys.create(\n    labels={\n        \"environment\": \"prod\",\n        \"example.com/my\": \"label\",\n        \"just-a-key\": \"\",\n    },\n    name=\"My ssh key\",\n    public_key=\"ssh-rsa AAAjjk76kgf...Xt\",\n)"
      - lang: Shell
        label: CLI
        source: "hcloud ssh-key create \\\n    --label \"environment=prod\" \\\n    --label \"example.com/my=label\" \\\n    --label \"just-a-key=\" \\\n    --name \"My ssh key\" \\\n    --public-key \"ssh-rsa AAAjjk76kgf...Xt\"\n#   --public-key-from-file ~/.ssh/id_rsa.pub"
  /ssh_keys/{id}:
    get:
      operationId: get_ssh_key
      summary: Get a SSH key
      description: Returns a specific SSH key object.
      tags:
      - SSH Keys
      parameters:
      - description: ID of the SSH Key.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [SSH Key](#tag/ssh-keys).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ssh_key:
                    type: object
                    properties:
                      id:
                        description: ID of the [SSH Key](#tag/ssh-keys).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      name:
                        description: Name of the Resource. Must be unique per Project.
                        type: string
                        example: my-resource
                      fingerprint:
                        description: MD5 fingerprint of the SSH public key.
                        type: string
                        example: b7:2f:30:a0:2f:6c:58:6c:21:04:58:61:ba:06:3b:2f
                      public_key:
                        description: Public key.
                        type: string
                        example: ssh-rsa AAAjjk76kgf...Xt
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                    required:
                    - id
                    - name
                    - fingerprint
                    - public_key
                    - labels
                    - created
                required:
                - ssh_key
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tsshKey, _, err := client.SSHKey.GetByID(ctx, 123)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          ssh_key = client.ssh_keys.get_by_id(123)'
      - lang: Shell
        label: CLI
        source: hcloud ssh-key describe $SSHKEY
    put:
      operationId: update_ssh_key
      summary: Update an SSH key
      description: Updates an SSH key. You can update an SSH key name and an SSH key labels.
      tags:
      - SSH Keys
      parameters:
      - description: ID of the SSH Key.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [SSH Key](#tag/ssh-keys).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: New name Name to set.
                  type: string
                  example: My ssh key
                labels:
                  description: 'User-defined labels (`key/value` pairs) for the Resource.


                    Note that the set of [Labels](#description/labels) provided in the request will overwrite the

                    existing one.


                    For more information, see "[Labels](#description/labels)".

                    '
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    environment: prod
                    example.com/my: label
                    just-a-key: ''
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ssh_key:
                    type: object
                    properties:
                      id:
                        description: ID of the [SSH Key](#tag/ssh-keys).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      name:
                        description: Name of the Resource. Must be unique per Project.
                        type: string
                        example: my-resource
                      fingerprint:
                        description: MD5 fingerprint of the SSH public key.
                        type: string
                        example: b7:2f:30:a0:2f:6c:58:6c:21:04:58:61:ba:06:3b:2f
                      public_key:
                        description: Public key.
                        type: string
                        example: ssh-rsa AAAjjk76kgf...Xt
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                    required:
                    - id
                    - name
                    - fingerprint
                    - public_key
                    - labels
                    - created
                required:
                - ssh_key
              examples:
                default:
                  value:
                    ssh_key:
                      id: 2323
                      name: My ssh key
                      fingerprint: b7:2f:30:a0:2f:6c:58:6c:21:04:58:61:ba:06:3b:2f
                      public_key: ssh-rsa AAAjjk76kgf...Xt
                      labels:
                        key: value
                      created: '2016-01-30T23:50:00Z'
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tsshKey, _, err := client.SSHKey.Update(ctx, &hcloud.SSHKey{ID: 123}, hcloud.SSHKeyUpdateOpts{\n\t\tLabels: map[string]string{\n\t\t\t\"environment\":    \"prod\",\n\t\t\t\"example.com/my\": \"label\",\n\t\t\t\"just-a-key\":     \"\",\n\t\t},\n\t\tName: \"My ssh key\",\n\t})\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\nfrom hcloud.ssh_keys import SSHKey\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nssh_key = client.ssh_keys.update(\n    ssh_key=SSHKey(id=123),\n    labels={\n        \"environment\": \"prod\",\n        \"example.com/my\": \"label\",\n        \"just-a-key\": \"\",\n    },\n    name=\"My ssh key\",\n)"
      - lang: Shell
        label: CLI
        source: "hcloud ssh-key update $SSHKEY --name \"My ssh key\"\nhcloud ssh-key add-label --overwrite $SSHKEY \\\n    \"environment=prod\" \"example.com/my=label\" \"just-a-key=\"\nhcloud ssh-key remove-label $SSHKEY \\\n    \"environment\" \"example.com\" \"just-a-key\""
    delete:
      operationId: delete_ssh_key
      summary: Delete an SSH key
      description: Deletes an SSH key. It cannot be used anymore.
      tags:
      - SSH Keys
      parameters:
      - description: ID of the SSH Key.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [SSH Key](#tag/ssh-keys).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '204':
          description: Request succeeded.
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\t_, err := client.SSHKey.Delete(ctx, &hcloud.SSHKey{ID: 123})\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\nfrom hcloud.ssh_keys import SSHKey\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nclient.ssh_keys.delete(\n    ssh_key=SSHKey(id=123),\n)"
      - lang: Shell
        label: CLI
        source: hcloud ssh-key delete $SSHKEY
components:
  securitySchemes:
    APIToken:
      type: http
      scheme: bearer
x-tagGroups:
- name: Actions
  tags:
  - Actions
- name: Servers
  tags:
  - Servers
  - Server Actions
  - Server Types
  - Images
  - Image Actions
  - ISOs
  - Placement Groups
  - Primary IPs
  - Primary IP Actions
- name: Volumes
  tags:
  - Volumes
  - Volume Actions
- name: Floating IPs
  tags:
  - Floating IPs
  - Floating IP Actions
- name: Firewalls
  tags:
  - Firewalls
  - Firewall Actions
- name: Load Balancers
  tags:
  - Load Balancers
  - Load Balancer Actions
  - Load Balancer Types
- name: Networks
  tags:
  - Networks
  - Network Actions
- name: DNS
  tags:
  - Zones
  - Zone Actions
  - Zone RRSets
  - Zone RRSet Actions
- name: Security
  tags:
  - Certificates
  - Certificate Actions
  - SSH Keys
- name: Locations
  tags:
  - Locations
  - Data Centers
- name: Billing
  tags:
  - Pricing
