openapi: 3.2.0
info:
  title: Hetzner Cloud Server Types API
  version: 1.0.0
  x-summary: 'Manage Hetzner Cloud services and resources linked to them, such as Floating IPs, Volumes and Load Balancers.

    '
  description: '# Overview


    This is the official documentation for the Hetzner Cloud API.'
servers:
- url: https://api.hetzner.cloud/v1
security:
- APIToken: []
tags:
- name: Server Types
  description: 'Server types define kinds of Servers offered. Each type has an hourly and a monthly cost. You will pay whichever cost is lower for your usage of this specific Server. Costs may differ between Locations.


    All prices are displayed in the currency of the project owner''s account.'
paths:
  /server_types:
    get:
      operationId: list_server_types
      summary: List Server Types
      description: Gets all Server type objects.
      tags:
      - Server Types
      parameters:
      - description: 'Filter resources by their name.


          The response will only contain the resources

          matching exactly the specified name.

          '
        name: name
        in: query
        required: false
        schema:
          type: string
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  server_types:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: ID of the Server type.
                          type: integer
                          format: int64
                          example: 1
                        name:
                          description: Unique identifier of the Server type.
                          type: string
                          example: cpx22
                        description:
                          description: Description of the Server type.
                          type: string
                          example: CPX22
                        cores:
                          description: Number of cpu cores a Server of this type will have.
                          type: number
                          example: 2
                        memory:
                          description: Memory a Server of this type will have in GB.
                          type: number
                          example: 4
                        disk:
                          description: Disk size a Server of this type will have in GB.
                          type: number
                          example: 80
                        deprecated:
                          description: This field is deprecated. Use the deprecation object instead.
                          type: boolean
                          example: false
                        prices:
                          description: Price per [Location](#tag/locations).
                          type: array
                          items:
                            type: object
                            properties:
                              location:
                                description: Name of the [Location](#tag/locations) the price is for.
                                type: string
                                example: fsn1
                              price_hourly:
                                description: Hourly price in this [Location](#tag/locations).
                                type: object
                                properties:
                                  net:
                                    description: Price without VAT.
                                    type: string
                                    format: decimal
                                    example: '1.0000'
                                  gross:
                                    description: Price with VAT added.
                                    type: string
                                    format: decimal
                                    example: '1.1900'
                                required:
                                - net
                                - gross
                              price_monthly:
                                description: Monthly price in this [Location](#tag/locations).
                                type: object
                                properties:
                                  net:
                                    description: Price without VAT.
                                    type: string
                                    format: decimal
                                    example: '1.0000'
                                  gross:
                                    description: Price with VAT added.
                                    type: string
                                    format: decimal
                                    example: '1.1900'
                                required:
                                - net
                                - gross
                              included_traffic:
                                description: Free traffic per month in bytes in this [Location](#tag/locations).
                                type: integer
                                format: int64
                                example: 654321
                              price_per_tb_traffic:
                                description: Additional traffic price per TB in this [Location](#tag/locations).
                                type: object
                                properties:
                                  net:
                                    description: Price without VAT.
                                    type: string
                                    format: decimal
                                    example: '1.0000'
                                  gross:
                                    description: Price with VAT added.
                                    type: string
                                    format: decimal
                                    example: '1.1900'
                                required:
                                - net
                                - gross
                            required:
                            - location
                            - price_hourly
                            - price_monthly
                            - included_traffic
                            - price_per_tb_traffic
                        storage_type:
                          description: Type of Server boot drive. Local has higher speed. Network has better availability.
                          type: string
                          enum:
                          - local
                          - network
                        cpu_type:
                          description: Type of cpu.
                          type: string
                          enum:
                          - shared
                          - dedicated
                          example: shared
                        category:
                          description: Category of Server Type.
                          type: string
                          example: Shared vCPU
                        architecture:
                          description: 'CPU architecture of the Server Type.

                            '
                          type: string
                          enum:
                          - x86
                          - arm
                          example: x86
                        deprecation:
                          deprecated: true
                          description: 'This field is deprecated.


                            Use the `deprecation` object in the `locations` field instead (`.locations[].deprecation`).

                            '
                          title: DeprecationInfo
                          type:
                          - object
                          - 'null'
                          properties:
                            unavailable_after:
                              description: 'Date of the deprecated resource removal.


                                Once this date is reached, the resource will not be returned

                                by resource type "list" endpoint, and the resource can not be

                                used to create new resources. For example, if this is an

                                image, you can not create new servers with this image after

                                the mentioned date.

                                '
                              type: string
                              format: date-time
                              example: '2023-09-01T00:00:00Z'
                            announced:
                              description: 'Date of the deprecation announcement.

                                '
                              type: string
                              format: date-time
                              example: '2023-06-01T00:00:00Z'
                          required:
                          - unavailable_after
                          - announced
                        locations:
                          description: "Supported [Location](#tag/locations) and per [Location](#tag/locations) details for the [Server Type](#tag/server-types).\n\nA [Server Type](#tag/server-types) is:\n - only supported in the [Location](#tag/locations) that are listed.\n - deprecated in the [Location](#tag/locations) when the `deprecation` property is set.\n - permanently unavailable in the [Location](#tag/locations) when the `deprecation.unavailable_after` date is in the past.\n - temporarily unavailable in the [Location](#tag/locations) when the `deprecation.available` is false.\n"
                          type: array
                          items:
                            description: 'A [Location](#tag/locations) (containing only id and name) and Server Type specific metadata.

                              '
                            type: object
                            properties:
                              id:
                                description: ID of the [Location](#tag/locations).
                                type: integer
                                format: int64
                                minimum: 1
                                maximum: 9007199254740991
                                example: 42
                              name:
                                description: Name of the [Location](#tag/locations).
                                type: string
                                example: fsn1
                              deprecation:
                                title: DeprecationInfo
                                description: 'Describes if, when and how the resource is deprecated. If this field is

                                  set to `null` the resource is not deprecated. If a value is set, it is

                                  considered deprecated.

                                  '
                                type:
                                - object
                                - 'null'
                                properties:
                                  unavailable_after:
                                    description: 'Date of the deprecated resource removal.


                                      Once this date is reached, the resource will not be returned

                                      by resource type "list" endpoint, and the resource can not be

                                      used to create new resources. For example, if this is an

                                      image, you can not create new servers with this image after

                                      the mentioned date.

                                      '
                                    type: string
                                    format: date-time
                                    example: '2023-09-01T00:00:00Z'
                                  announced:
                                    description: 'Date of the deprecation announcement.

                                      '
                                    type: string
                                    format: date-time
                                    example: '2023-06-01T00:00:00Z'
                                required:
                                - unavailable_after
                                - announced
                              recommended:
                                description: 'Whether the [Server Type](#tag/server-types) is recommended in this [Location](#tag/locations).

                                  '
                                type: boolean
                                example: false
                              available:
                                description: 'Whether the [Server Type](#tag/server-types) is temporarily unavailable in this [Location](#tag/locations).

                                  '
                                type: boolean
                                example: true
                            required:
                            - id
                            - name
                            - deprecation
                            - recommended
                            - available
                      required:
                      - id
                      - name
                      - description
                      - cores
                      - memory
                      - disk
                      - deprecated
                      - prices
                      - storage_type
                      - cpu_type
                      - architecture
                      - locations
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - server_types
                - meta
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tserverTypes, err := client.ServerType.All(ctx)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          server_types = client.server_types.get_all()'
      - lang: Shell
        label: CLI
        source: hcloud server-type list
  /server_types/{id}:
    get:
      operationId: get_server_type
      summary: Get a Server Type
      description: Gets a specific Server type object.
      tags:
      - Server Types
      parameters:
      - description: ID of the Server Type.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Server Type](#tag/server-types).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  server_type:
                    type: object
                    properties:
                      id:
                        description: ID of the Server type.
                        type: integer
                        format: int64
                        example: 1
                      name:
                        description: Unique identifier of the Server type.
                        type: string
                        example: cpx22
                      description:
                        description: Description of the Server type.
                        type: string
                        example: CPX22
                      cores:
                        description: Number of cpu cores a Server of this type will have.
                        type: number
                        example: 2
                      memory:
                        description: Memory a Server of this type will have in GB.
                        type: number
                        example: 4
                      disk:
                        description: Disk size a Server of this type will have in GB.
                        type: number
                        example: 80
                      deprecated:
                        description: This field is deprecated. Use the deprecation object instead.
                        type: boolean
                        example: false
                      prices:
                        description: Price per [Location](#tag/locations).
                        type: array
                        items:
                          type: object
                          properties:
                            location:
                              description: Name of the [Location](#tag/locations) the price is for.
                              type: string
                              example: fsn1
                            price_hourly:
                              description: Hourly price in this [Location](#tag/locations).
                              type: object
                              properties:
                                net:
                                  description: Price without VAT.
                                  type: string
                                  format: decimal
                                  example: '1.0000'
                                gross:
                                  description: Price with VAT added.
                                  type: string
                                  format: decimal
                                  example: '1.1900'
                              required:
                              - net
                              - gross
                            price_monthly:
                              description: Monthly price in this [Location](#tag/locations).
                              type: object
                              properties:
                                net:
                                  description: Price without VAT.
                                  type: string
                                  format: decimal
                                  example: '1.0000'
                                gross:
                                  description: Price with VAT added.
                                  type: string
                                  format: decimal
                                  example: '1.1900'
                              required:
                              - net
                              - gross
                            included_traffic:
                              description: Free traffic per month in bytes in this [Location](#tag/locations).
                              type: integer
                              format: int64
                              example: 654321
                            price_per_tb_traffic:
                              description: Additional traffic price per TB in this [Location](#tag/locations).
                              type: object
                              properties:
                                net:
                                  description: Price without VAT.
                                  type: string
                                  format: decimal
                                  example: '1.0000'
                                gross:
                                  description: Price with VAT added.
                                  type: string
                                  format: decimal
                                  example: '1.1900'
                              required:
                              - net
                              - gross
                          required:
                          - location
                          - price_hourly
                          - price_monthly
                          - included_traffic
                          - price_per_tb_traffic
                      storage_type:
                        description: Type of Server boot drive. Local has higher speed. Network has better availability.
                        type: string
                        enum:
                        - local
                        - network
                      cpu_type:
                        description: Type of cpu.
                        type: string
                        enum:
                        - shared
                        - dedicated
                        example: shared
                      category:
                        description: Category of Server Type.
                        type: string
                        example: Shared vCPU
                      architecture:
                        description: 'CPU architecture of the Server Type.

                          '
                        type: string
                        enum:
                        - x86
                        - arm
                        example: x86
                      deprecation:
                        deprecated: true
                        description: 'This field is deprecated.


                          Use the `deprecation` object in the `locations` field instead (`.locations[].deprecation`).

                          '
                        title: DeprecationInfo
                        type:
                        - object
                        - 'null'
                        properties:
                          unavailable_after:
                            description: 'Date of the deprecated resource removal.


                              Once this date is reached, the resource will not be returned

                              by resource type "list" endpoint, and the resource can not be

                              used to create new resources. For example, if this is an

                              image, you can not create new servers with this image after

                              the mentioned date.

                              '
                            type: string
                            format: date-time
                            example: '2023-09-01T00:00:00Z'
                          announced:
                            description: 'Date of the deprecation announcement.

                              '
                            type: string
                            format: date-time
                            example: '2023-06-01T00:00:00Z'
                        required:
                        - unavailable_after
                        - announced
                      locations:
                        description: "Supported [Location](#tag/locations) and per [Location](#tag/locations) details for the [Server Type](#tag/server-types).\n\nA [Server Type](#tag/server-types) is:\n - only supported in the [Location](#tag/locations) that are listed.\n - deprecated in the [Location](#tag/locations) when the `deprecation` property is set.\n - permanently unavailable in the [Location](#tag/locations) when the `deprecation.unavailable_after` date is in the past.\n - temporarily unavailable in the [Location](#tag/locations) when the `deprecation.available` is false.\n"
                        type: array
                        items:
                          description: 'A [Location](#tag/locations) (containing only id and name) and Server Type specific metadata.

                            '
                          type: object
                          properties:
                            id:
                              description: ID of the [Location](#tag/locations).
                              type: integer
                              format: int64
                              minimum: 1
                              maximum: 9007199254740991
                              example: 42
                            name:
                              description: Name of the [Location](#tag/locations).
                              type: string
                              example: fsn1
                            deprecation:
                              title: DeprecationInfo
                              description: 'Describes if, when and how the resource is deprecated. If this field is

                                set to `null` the resource is not deprecated. If a value is set, it is

                                considered deprecated.

                                '
                              type:
                              - object
                              - 'null'
                              properties:
                                unavailable_after:
                                  description: 'Date of the deprecated resource removal.


                                    Once this date is reached, the resource will not be returned

                                    by resource type "list" endpoint, and the resource can not be

                                    used to create new resources. For example, if this is an

                                    image, you can not create new servers with this image after

                                    the mentioned date.

                                    '
                                  type: string
                                  format: date-time
                                  example: '2023-09-01T00:00:00Z'
                                announced:
                                  description: 'Date of the deprecation announcement.

                                    '
                                  type: string
                                  format: date-time
                                  example: '2023-06-01T00:00:00Z'
                              required:
                              - unavailable_after
                              - announced
                            recommended:
                              description: 'Whether the [Server Type](#tag/server-types) is recommended in this [Location](#tag/locations).

                                '
                              type: boolean
                              example: false
                            available:
                              description: 'Whether the [Server Type](#tag/server-types) is temporarily unavailable in this [Location](#tag/locations).

                                '
                              type: boolean
                              example: true
                          required:
                          - id
                          - name
                          - deprecation
                          - recommended
                          - available
                    required:
                    - id
                    - name
                    - description
                    - cores
                    - memory
                    - disk
                    - deprecated
                    - prices
                    - storage_type
                    - cpu_type
                    - architecture
                    - locations
                required:
                - server_type
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tserverType, _, err := client.ServerType.GetByID(ctx, 123)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          server_type = client.server_types.get_by_id(123)'
      - lang: Shell
        label: CLI
        source: hcloud server-type describe $SERVERTYPE
components:
  securitySchemes:
    APIToken:
      type: http
      scheme: bearer
x-tagGroups:
- name: Actions
  tags:
  - Actions
- name: Servers
  tags:
  - Servers
  - Server Actions
  - Server Types
  - Images
  - Image Actions
  - ISOs
  - Placement Groups
  - Primary IPs
  - Primary IP Actions
- name: Volumes
  tags:
  - Volumes
  - Volume Actions
- name: Floating IPs
  tags:
  - Floating IPs
  - Floating IP Actions
- name: Firewalls
  tags:
  - Firewalls
  - Firewall Actions
- name: Load Balancers
  tags:
  - Load Balancers
  - Load Balancer Actions
  - Load Balancer Types
- name: Networks
  tags:
  - Networks
  - Network Actions
- name: DNS
  tags:
  - Zones
  - Zone Actions
  - Zone RRSets
  - Zone RRSet Actions
- name: Security
  tags:
  - Certificates
  - Certificate Actions
  - SSH Keys
- name: Locations
  tags:
  - Locations
  - Data Centers
- name: Billing
  tags:
  - Pricing
