openapi: 3.2.0
info:
  title: Hetzner Cloud Images API
  version: 1.0.0
  x-summary: 'Manage Hetzner Cloud services and resources linked to them, such as Floating IPs, Volumes and Load Balancers.

    '
  description: '# Overview


    This is the official documentation for the Hetzner Cloud API.'
servers:
- url: https://api.hetzner.cloud/v1
security:
- APIToken: []
tags:
- name: Images
  description: Images are blueprints for your VM disks.
paths:
  /images:
    get:
      operationId: list_images
      summary: List Images
      description: Returns all Image objects. You can select specific Image types only and sort the results by using URI parameters.
      tags:
      - Images
      parameters:
      - description: 'Sort resources by field and direction. May be used multiple times.


          For more information, see "[Sorting](#description/sorting)".

          '
        name: sort
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - id
            - id:asc
            - id:desc
            - name
            - name:asc
            - name:desc
            - created
            - created:asc
            - created:desc
      - description: 'Filter resources by type. May be used multiple times.


          The response will only contain the resources with the specified type.

          '
        name: type
        in: query
        required: false
        schema:
          type: array
          items:
            description: Type of the Image.
            type: string
            enum:
            - system
            - app
            - snapshot
            - backup
            example: snapshot
      - description: 'Filter resources by status. May be used multiple times.


          The response will only contain the resources with the specified status.

          '
        name: status
        in: query
        required: false
        schema:
          type: array
          items:
            description: Status of the Image.
            type: string
            enum:
            - available
            - creating
            - unavailable
            example: available
      - description: 'Filter Images by their linked Server ID. May be used multiple times.


          Only available for Images of type `backup`.

          '
        name: bound_to
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      - description: Include deprecated Images.
        name: include_deprecated
        in: query
        required: false
        schema:
          type: boolean
      - description: 'Filter resources by their name.


          The response will only contain the resources

          matching exactly the specified name.

          '
        name: name
        in: query
        required: false
        schema:
          type: string
      - description: 'Filter resources by labels.


          The response will only contain resources matching the label selector.

          For more information, see "[Label Selector](#description/label-selector)".

          '
        name: label_selector
        in: query
        required: false
        schema:
          type: string
      - description: 'Filter resources by cpu architecture.


          The response will only contain the resources with the specified cpu architecture.

          '
        name: architecture
        in: query
        required: false
        schema:
          description: CPU architecture of the Resource.
          type: string
          enum:
          - x86
          - arm
          example: x86
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          description: ID of the [Image](#tag/images).
                          type: integer
                          format: int64
                          minimum: 1
                          maximum: 9007199254740991
                          example: 42
                        type:
                          description: Type of the Image.
                          type: string
                          enum:
                          - system
                          - app
                          - snapshot
                          - backup
                          example: snapshot
                        status:
                          description: Status of the Image.
                          type: string
                          enum:
                          - available
                          - creating
                          - unavailable
                          example: available
                        name:
                          description: Unique identifier of the Image. This value is only set for system Images.
                          type:
                          - string
                          - 'null'
                          example: ubuntu-24.04
                        description:
                          description: Description of the Image.
                          type: string
                          example: Ubuntu 24.04 Standard 64 bit
                        image_size:
                          description: Size of the Image file in our storage in GB. For snapshot Images this is the value relevant for calculating costs for the Image.
                          type:
                          - number
                          - 'null'
                          example: 2.3
                        disk_size:
                          description: Size of the disk contained in the Image in GB.
                          type: number
                          example: 10
                        created:
                          description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type: string
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                        created_from:
                          description: Information about the Server the Image was created from.
                          type:
                          - object
                          - 'null'
                          properties:
                            id:
                              description: ID of the Server the Image was created from.
                              type: integer
                              format: int64
                              example: 1
                            name:
                              description: Server name at the time the Image was created.
                              type: string
                              example: Server
                          required:
                          - id
                          - name
                        bound_to:
                          description: ID of Server the Image is bound to. Only set for Images of type `backup`.
                          type:
                          - integer
                          - 'null'
                          format: int64
                          example: null
                        os_flavor:
                          description: Flavor of operating system contained in the Image.
                          type: string
                          enum:
                          - ubuntu
                          - centos
                          - debian
                          - fedora
                          - rocky
                          - alma
                          - opensuse
                          - unknown
                          example: ubuntu
                        os_version:
                          description: Operating system version.
                          type:
                          - string
                          - 'null'
                          example: '24.04'
                        rapid_deploy:
                          description: Indicates that rapid deploy of the Image is available.
                          type: boolean
                          example: false
                        protection:
                          description: Protection configuration for the Resource.
                          type: object
                          properties:
                            delete:
                              description: Prevent the Resource from being deleted.
                              type: boolean
                              example: false
                          required:
                          - delete
                        deprecated:
                          description: Point in time when the Image is considered to be deprecated (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type:
                          - string
                          - 'null'
                          format: date-time
                          example: '2018-02-28T00:00:00Z'
                        deleted:
                          description: Point in time where the Image was deleted (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type:
                          - string
                          - 'null'
                          example: null
                        labels:
                          description: 'User-defined labels (`key/value` pairs) for the Resource.

                            For more information, see "[Labels](#description/labels)".

                            '
                          type: object
                          additionalProperties:
                            type: string
                          example:
                            environment: prod
                            example.com/my: label
                            just-a-key: ''
                        architecture:
                          description: 'CPU architecture compatible with the Image.

                            '
                          type: string
                          enum:
                          - x86
                          - arm
                          example: x86
                      required:
                      - id
                      - type
                      - status
                      - name
                      - description
                      - image_size
                      - disk_size
                      - created
                      - created_from
                      - bound_to
                      - os_flavor
                      - os_version
                      - protection
                      - deprecated
                      - deleted
                      - labels
                      - architecture
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - images
                - meta
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\timages, err := client.Image.All(ctx)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          images = client.images.get_all()'
      - lang: Shell
        label: CLI
        source: hcloud image list
  /images/{id}:
    get:
      operationId: get_image
      summary: Get an Image
      description: Returns a specific Image object.
      tags:
      - Images
      parameters:
      - description: ID of the Image.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Image](#tag/images).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: object
                    properties:
                      id:
                        description: ID of the [Image](#tag/images).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      type:
                        description: Type of the Image.
                        type: string
                        enum:
                        - system
                        - app
                        - snapshot
                        - backup
                        example: snapshot
                      status:
                        description: Status of the Image.
                        type: string
                        enum:
                        - available
                        - creating
                        - unavailable
                        example: available
                      name:
                        description: Unique identifier of the Image. This value is only set for system Images.
                        type:
                        - string
                        - 'null'
                        example: ubuntu-24.04
                      description:
                        description: Description of the Image.
                        type: string
                        example: Ubuntu 24.04 Standard 64 bit
                      image_size:
                        description: Size of the Image file in our storage in GB. For snapshot Images this is the value relevant for calculating costs for the Image.
                        type:
                        - number
                        - 'null'
                        example: 2.3
                      disk_size:
                        description: Size of the disk contained in the Image in GB.
                        type: number
                        example: 10
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      created_from:
                        description: Information about the Server the Image was created from.
                        type:
                        - object
                        - 'null'
                        properties:
                          id:
                            description: ID of the Server the Image was created from.
                            type: integer
                            format: int64
                            example: 1
                          name:
                            description: Server name at the time the Image was created.
                            type: string
                            example: Server
                        required:
                        - id
                        - name
                      bound_to:
                        description: ID of Server the Image is bound to. Only set for Images of type `backup`.
                        type:
                        - integer
                        - 'null'
                        format: int64
                        example: null
                      os_flavor:
                        description: Flavor of operating system contained in the Image.
                        type: string
                        enum:
                        - ubuntu
                        - centos
                        - debian
                        - fedora
                        - rocky
                        - alma
                        - opensuse
                        - unknown
                        example: ubuntu
                      os_version:
                        description: Operating system version.
                        type:
                        - string
                        - 'null'
                        example: '24.04'
                      rapid_deploy:
                        description: Indicates that rapid deploy of the Image is available.
                        type: boolean
                        example: false
                      protection:
                        description: Protection configuration for the Resource.
                        type: object
                        properties:
                          delete:
                            description: Prevent the Resource from being deleted.
                            type: boolean
                            example: false
                        required:
                        - delete
                      deprecated:
                        description: Point in time when the Image is considered to be deprecated (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2018-02-28T00:00:00Z'
                      deleted:
                        description: Point in time where the Image was deleted (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type:
                        - string
                        - 'null'
                        example: null
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      architecture:
                        description: 'CPU architecture compatible with the Image.

                          '
                        type: string
                        enum:
                        - x86
                        - arm
                        example: x86
                    required:
                    - id
                    - type
                    - status
                    - name
                    - description
                    - image_size
                    - disk_size
                    - created
                    - created_from
                    - bound_to
                    - os_flavor
                    - os_version
                    - protection
                    - deprecated
                    - deleted
                    - labels
                    - architecture
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\timage, _, err := client.Image.GetByID(ctx, 123)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          image = client.images.get_by_id(123)'
      - lang: Shell
        label: CLI
        source: hcloud image describe $IMAGE
    put:
      operationId: update_image
      summary: Update an Image
      description: Updates the Image. You may change the description, convert a Backup Image to a Snapshot Image or change the Image labels. Only Images of type `snapshot` and `backup` can be updated.
      tags:
      - Images
      parameters:
      - description: ID of the Image.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Image](#tag/images).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: UpdateImageRequest
              type: object
              properties:
                description:
                  description: New description of Image.
                  type: string
                  example: My new Image description
                type:
                  description: Destination Image type to convert to.
                  type: string
                  enum:
                  - snapshot
                labels:
                  description: 'User-defined labels (`key/value` pairs) for the Resource.


                    Note that the set of [Labels](#description/labels) provided in the request will overwrite the

                    existing one.


                    For more information, see "[Labels](#description/labels)".

                    '
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    environment: prod
                    example.com/my: label
                    just-a-key: ''
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: object
                    properties:
                      id:
                        description: ID of the [Image](#tag/images).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      type:
                        description: Type of the Image.
                        type: string
                        enum:
                        - system
                        - app
                        - snapshot
                        - backup
                        example: snapshot
                      status:
                        description: Status of the Image.
                        type: string
                        enum:
                        - available
                        - creating
                        - unavailable
                        example: available
                      name:
                        description: Unique identifier of the Image. This value is only set for system Images.
                        type:
                        - string
                        - 'null'
                        example: ubuntu-24.04
                      description:
                        description: Description of the Image.
                        type: string
                        example: Ubuntu 24.04 Standard 64 bit
                      image_size:
                        description: Size of the Image file in our storage in GB. For snapshot Images this is the value relevant for calculating costs for the Image.
                        type:
                        - number
                        - 'null'
                        example: 2.3
                      disk_size:
                        description: Size of the disk contained in the Image in GB.
                        type: number
                        example: 10
                      created:
                        description: Point in time when the Resource was created (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      created_from:
                        description: Information about the Server the Image was created from.
                        type:
                        - object
                        - 'null'
                        properties:
                          id:
                            description: ID of the Server the Image was created from.
                            type: integer
                            format: int64
                            example: 1
                          name:
                            description: Server name at the time the Image was created.
                            type: string
                            example: Server
                        required:
                        - id
                        - name
                      bound_to:
                        description: ID of Server the Image is bound to. Only set for Images of type `backup`.
                        type:
                        - integer
                        - 'null'
                        format: int64
                        example: null
                      os_flavor:
                        description: Flavor of operating system contained in the Image.
                        type: string
                        enum:
                        - ubuntu
                        - centos
                        - debian
                        - fedora
                        - rocky
                        - alma
                        - opensuse
                        - unknown
                        example: ubuntu
                      os_version:
                        description: Operating system version.
                        type:
                        - string
                        - 'null'
                        example: '24.04'
                      rapid_deploy:
                        description: Indicates that rapid deploy of the Image is available.
                        type: boolean
                        example: false
                      protection:
                        description: Protection configuration for the Resource.
                        type: object
                        properties:
                          delete:
                            description: Prevent the Resource from being deleted.
                            type: boolean
                            example: false
                        required:
                        - delete
                      deprecated:
                        description: Point in time when the Image is considered to be deprecated (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2018-02-28T00:00:00Z'
                      deleted:
                        description: Point in time where the Image was deleted (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type:
                        - string
                        - 'null'
                        example: null
                      labels:
                        description: 'User-defined labels (`key/value` pairs) for the Resource.

                          For more information, see "[Labels](#description/labels)".

                          '
                        type: object
                        additionalProperties:
                          type: string
                        example:
                          environment: prod
                          example.com/my: label
                          just-a-key: ''
                      architecture:
                        description: 'CPU architecture compatible with the Image.

                          '
                        type: string
                        enum:
                        - x86
                        - arm
                        example: x86
                    required:
                    - id
                    - type
                    - status
                    - name
                    - description
                    - image_size
                    - disk_size
                    - created
                    - created_from
                    - bound_to
                    - os_flavor
                    - os_version
                    - protection
                    - deprecated
                    - deleted
                    - labels
                    - architecture
              examples:
                default:
                  value:
                    image:
                      id: 4711
                      type: snapshot
                      status: available
                      name: null
                      description: My new Image description
                      image_size: 2.3
                      disk_size: 10
                      created: '2016-01-30T23:50:00Z'
                      created_from:
                        id: 1
                        name: Server
                      bound_to: null
                      os_flavor: ubuntu
                      os_version: '20.04'
                      rapid_deploy: false
                      protection:
                        delete: false
                      deprecated: '2018-02-28T00:00:00Z'
                      deleted: null
                      labels:
                        key: value
                      architecture: x86
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\timage, _, err := client.Image.Update(ctx, &hcloud.Image{ID: 123}, hcloud.ImageUpdateOpts{\n\t\tDescription: hcloud.Ptr(\"My new Image description\"),\n\t\tLabels: map[string]string{\n\t\t\t\"environment\":    \"prod\",\n\t\t\t\"example.com/my\": \"label\",\n\t\t\t\"just-a-key\":     \"\",\n\t\t},\n\t\tType: hcloud.ImageTypeSnapshot,\n\t})\n}"
      - lang: Python
        label: Python
        source: "from __future__ import annotations\n\nfrom os import environ\n\nfrom hcloud import Client\nfrom hcloud.images import Image\n\ntoken = environ[\"HCLOUD_TOKEN\"]\nclient = Client(token=token)\n\nimage = client.images.update(\n    image=Image(id=123),\n    description=\"My new Image description\",\n    labels={\n        \"environment\": \"prod\",\n        \"example.com/my\": \"label\",\n        \"just-a-key\": \"\",\n    },\n    type=\"snapshot\",\n)"
      - lang: Shell
        label: CLI
        source: "hcloud image update $IMAGE --description \"My new Image description\"\nhcloud image add-label --overwrite $IMAGE \\\n    \"environment=prod\" \"example.com/my=label\" \"just-a-key=\"\nhcloud image remove-label $IMAGE \\\n    \"environment\" \"example.com\" \"just-a-key\""
    delete:
      operationId: delete_image
      summary: Delete an Image
      description: Deletes an Image. Only Images of type `snapshot` and `backup` can be deleted.
      tags:
      - Images
      parameters:
      - description: ID of the Image.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Image](#tag/images).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '204':
          description: Request succeeded.
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\t_, err := client.Image.Delete(ctx, &hcloud.Image{ID: 123})\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client

          from hcloud.images import Image


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          image = client.images.delete(Image(id=123))'
      - lang: Shell
        label: CLI
        source: hcloud image delete $IMAGE
components:
  securitySchemes:
    APIToken:
      type: http
      scheme: bearer
x-tagGroups:
- name: Actions
  tags:
  - Actions
- name: Servers
  tags:
  - Servers
  - Server Actions
  - Server Types
  - Images
  - Image Actions
  - ISOs
  - Placement Groups
  - Primary IPs
  - Primary IP Actions
- name: Volumes
  tags:
  - Volumes
  - Volume Actions
- name: Floating IPs
  tags:
  - Floating IPs
  - Floating IP Actions
- name: Firewalls
  tags:
  - Firewalls
  - Firewall Actions
- name: Load Balancers
  tags:
  - Load Balancers
  - Load Balancer Actions
  - Load Balancer Types
- name: Networks
  tags:
  - Networks
  - Network Actions
- name: DNS
  tags:
  - Zones
  - Zone Actions
  - Zone RRSets
  - Zone RRSet Actions
- name: Security
  tags:
  - Certificates
  - Certificate Actions
  - SSH Keys
- name: Locations
  tags:
  - Locations
  - Data Centers
- name: Billing
  tags:
  - Pricing
