openapi: 3.2.0
info:
  title: Hetzner Cloud Certificate Actions API
  version: 1.0.0
  x-summary: 'Manage Hetzner Cloud services and resources linked to them, such as Floating IPs, Volumes and Load Balancers.

    '
  description: '# Overview


    This is the official documentation for the Hetzner Cloud API.'
servers:
- url: https://api.hetzner.cloud/v1
security:
- APIToken: []
tags:
- name: Certificate Actions
paths:
  /certificates/actions:
    get:
      operationId: list_certificates_actions
      summary: List Actions
      description: Returns all Action objects. You can `sort` the results by using the sort URI parameter, and filter them with the `status` and `id` parameter.
      tags:
      - Certificate Actions
      parameters:
      - description: 'Filter the actions by ID. May be used multiple times.


          The response will only contain actions matching the specified IDs.

          '
        name: id
        in: query
        required: false
        schema:
          type: array
          items:
            description: ID of the [Action](#description/actions).
            type: integer
            format: int64
            minimum: 1
            maximum: 9007199254740991
            example: 42
      - description: 'Sort actions by field and direction. May be used multiple times.


          For more information, see "[Sorting](#description/sorting)".

          '
        name: sort
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - id
            - id:asc
            - id:desc
            - command
            - command:asc
            - command:desc
            - status
            - status:asc
            - status:desc
            - started
            - started:asc
            - started:desc
            - finished
            - finished:asc
            - finished:desc
      - description: 'Filter the actions by status. May be used multiple times.


          The response will only contain actions matching the specified statuses.

          '
        name: status
        in: query
        required: false
        schema:
          type: array
          items:
            description: Status of the Action.
            type: string
            enum:
            - running
            - success
            - error
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: ActionListResponseWithMeta
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      title: Action
                      type: object
                      properties:
                        id:
                          description: ID of the [Action](#description/actions).
                          type: integer
                          format: int64
                          minimum: 1
                          maximum: 9007199254740991
                          example: 42
                        command:
                          description: Command executed in the Action.
                          type: string
                          example: start_resource
                        status:
                          description: Status of the Action.
                          type: string
                          enum:
                          - running
                          - success
                          - error
                        started:
                          description: Point in time when the Action was started (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type: string
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                        finished:
                          description: Point in time when the Action was finished (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format). Only set if the Action is finished otherwise null.
                          type:
                          - string
                          - 'null'
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                        progress:
                          description: Progress of the Action in percent.
                          type: integer
                          format: int32
                          example: 100
                        resources:
                          description: Resources the Action relates to.
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                description: ID of the Resource.
                                type: integer
                                format: int64
                                minimum: 1
                                maximum: 9007199254740991
                                example: 42
                              type:
                                description: Type of the Resource.
                                type: string
                                example: server
                            required:
                            - id
                            - type
                        error:
                          description: Error message for the Action if an error occurred, otherwise null.
                          type:
                          - object
                          - 'null'
                          properties:
                            code:
                              description: Fixed error code for machines.
                              type: string
                              example: action_failed
                            message:
                              description: Error message for humans.
                              type: string
                              example: Action failed
                          required:
                          - code
                          - message
                      required:
                      - id
                      - command
                      - status
                      - progress
                      - started
                      - finished
                      - resources
                      - error
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - actions
                - meta
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\tactions, err := client.Certificate.Action.All(ctx, hcloud.ActionListOpts{})\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          actions = client.certificates.actions.get_all()'
  /certificates/actions/{id}:
    get:
      operationId: get_certificates_action
      summary: Get an Action
      description: Returns a specific Action object.
      tags:
      - Certificate Actions
      parameters:
      - description: ID of the Action.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Action](#description/actions).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: ActionResponse
                type: object
                properties:
                  action:
                    title: Action
                    type: object
                    properties:
                      id:
                        description: ID of the [Action](#description/actions).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      command:
                        description: Command executed in the Action.
                        type: string
                        example: start_resource
                      status:
                        description: Status of the Action.
                        type: string
                        enum:
                        - running
                        - success
                        - error
                      started:
                        description: Point in time when the Action was started (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      finished:
                        description: Point in time when the Action was finished (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format). Only set if the Action is finished otherwise null.
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      progress:
                        description: Progress of the Action in percent.
                        type: integer
                        format: int32
                        example: 100
                      resources:
                        description: Resources the Action relates to.
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              description: ID of the Resource.
                              type: integer
                              format: int64
                              minimum: 1
                              maximum: 9007199254740991
                              example: 42
                            type:
                              description: Type of the Resource.
                              type: string
                              example: server
                          required:
                          - id
                          - type
                      error:
                        description: Error message for the Action if an error occurred, otherwise null.
                        type:
                        - object
                        - 'null'
                        properties:
                          code:
                            description: Fixed error code for machines.
                            type: string
                            example: action_failed
                          message:
                            description: Error message for humans.
                            type: string
                            example: Action failed
                        required:
                        - code
                        - message
                    required:
                    - id
                    - command
                    - status
                    - progress
                    - started
                    - finished
                    - resources
                    - error
                required:
                - action
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\taction, _, err := client.Certificate.Action.GetByID(ctx, 123)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          action = client.certificates.actions.get_by_id(123)'
  /certificates/{id}/actions:
    get:
      operationId: list_certificate_actions
      summary: List Actions for a Certificate
      description: 'Returns all Action objects for a Certificate. You can sort the results by using the `sort` URI parameter, and filter them with the `status` parameter.


        Only type `managed` Certificates can have Actions. For type `uploaded` Certificates the `actions` key will always contain an empty array.'
      tags:
      - Certificate Actions
      parameters:
      - description: ID of the Certificate.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Certificate](#tag/certificates).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      - description: 'Sort actions by field and direction. May be used multiple times.


          For more information, see "[Sorting](#description/sorting)".

          '
        name: sort
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - id
            - id:asc
            - id:desc
            - command
            - command:asc
            - command:desc
            - status
            - status:asc
            - status:desc
            - started
            - started:asc
            - started:desc
            - finished
            - finished:asc
            - finished:desc
      - description: 'Filter the actions by status. May be used multiple times.


          The response will only contain actions matching the specified statuses.

          '
        name: status
        in: query
        required: false
        schema:
          type: array
          items:
            description: Status of the Action.
            type: string
            enum:
            - running
            - success
            - error
      - description: Page number to return. For more information, see "[Pagination](#description/pagination)".
        name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 1
          example: 1
      - description: Maximum number of entries returned per page. For more information, see "[Pagination](#description/pagination)".
        name: per_page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          default: 25
          example: 25
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: ActionListResponseWithMeta
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      title: Action
                      type: object
                      properties:
                        id:
                          description: ID of the [Action](#description/actions).
                          type: integer
                          format: int64
                          minimum: 1
                          maximum: 9007199254740991
                          example: 42
                        command:
                          description: Command executed in the Action.
                          type: string
                          example: start_resource
                        status:
                          description: Status of the Action.
                          type: string
                          enum:
                          - running
                          - success
                          - error
                        started:
                          description: Point in time when the Action was started (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                          type: string
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                        finished:
                          description: Point in time when the Action was finished (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format). Only set if the Action is finished otherwise null.
                          type:
                          - string
                          - 'null'
                          format: date-time
                          example: '2016-01-30T23:55:00Z'
                        progress:
                          description: Progress of the Action in percent.
                          type: integer
                          format: int32
                          example: 100
                        resources:
                          description: Resources the Action relates to.
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                description: ID of the Resource.
                                type: integer
                                format: int64
                                minimum: 1
                                maximum: 9007199254740991
                                example: 42
                              type:
                                description: Type of the Resource.
                                type: string
                                example: server
                            required:
                            - id
                            - type
                        error:
                          description: Error message for the Action if an error occurred, otherwise null.
                          type:
                          - object
                          - 'null'
                          properties:
                            code:
                              description: Fixed error code for machines.
                              type: string
                              example: action_failed
                            message:
                              description: Error message for humans.
                              type: string
                              example: Action failed
                          required:
                          - code
                          - message
                      required:
                      - id
                      - command
                      - status
                      - progress
                      - started
                      - finished
                      - resources
                      - error
                  meta:
                    title: ListMeta
                    type: object
                    properties:
                      pagination:
                        description: See "[Pagination](#description/pagination)" for more information.
                        type: object
                        properties:
                          page:
                            description: Current page number.
                            type: integer
                            format: int64
                            example: 3
                          per_page:
                            description: Maximum number of entries returned per page.
                            type: integer
                            format: int64
                            example: 25
                          previous_page:
                            description: Page number of the previous page. Can be null if the current page is the first one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 2
                          next_page:
                            description: Page number of the next page. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          last_page:
                            description: Page number of the last page available. Can be null if the current page is the last one.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 4
                          total_entries:
                            description: Total number of entries that exist for this query. Can be null if unknown.
                            type:
                            - integer
                            - 'null'
                            format: int64
                            example: 100
                        required:
                        - page
                        - per_page
                        - previous_page
                        - next_page
                        - last_page
                        - total_entries
                    required:
                    - pagination
                required:
                - actions
                - meta
              examples:
                default:
                  value:
                    actions:
                    - id: 14
                      command: issue_certificate
                      status: success
                      progress: 100
                      started: '2021-01-30T23:55:00Z'
                      finished: '2021-01-30T23:57:00Z'
                      resources:
                      - id: 896
                        type: certificate
                      error:
                        code: action_failed
                        message: Action failed
                    meta:
                      pagination:
                        page: 1
                        per_page: 25
                        previous_page: null
                        next_page: null
                        last_page: 1
                        total_entries: 21
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
  /certificates/{id}/actions/retry:
    post:
      operationId: retry_certificate
      summary: Retry Issuance or Renewal
      description: 'Retry a failed Certificate issuance or renewal.


        Only applicable if the type of the Certificate is `managed` and the issuance or renewal status is `failed`.


        #### Operation specific errors


        | Status | Code | Description |

        | --- | --- | --- |

        | | `caa_record_does_not_allow_ca` | CAA record does not allow certificate authority |

        | | `ca_dns_validation_failed` | Certificate Authority: DNS validation failed |

        | | `ca_too_many_authorizations_failed_recently` | Certificate Authority: Too many authorizations failed recently |

        | | `ca_too_many_certificates_issued_for_registered_domain` | Certificate Authority: Too many certificates issued for registered domain |

        | | `ca_too_many_duplicate_certificates` | Certificate Authority: Too many duplicate certificates |

        | | `could_not_verify_domain_delegated_to_zone` | Could not verify domain delegated to zone |

        | | `dns_zone_not_found` | DNS zone not found |

        | | `dns_zone_is_secondary_zone` | DNS zone is a secondary zone |'
      tags:
      - Certificate Actions
      parameters:
      - description: ID of the Certificate.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Certificate](#tag/certificates).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '201':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: ActionResponse
                description: 'Response for a created [Action](#description/actions).


                  Make sure to wait for the [Action](#description/actions) completion to ensure your changes are applied.

                  '
                type: object
                properties:
                  action:
                    title: Action
                    type: object
                    properties:
                      id:
                        description: ID of the [Action](#description/actions).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      command:
                        description: Command executed in the Action.
                        type: string
                        example: start_resource
                      status:
                        description: Status of the Action.
                        type: string
                        enum:
                        - running
                        - success
                        - error
                      started:
                        description: Point in time when the Action was started (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      finished:
                        description: Point in time when the Action was finished (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format). Only set if the Action is finished otherwise null.
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      progress:
                        description: Progress of the Action in percent.
                        type: integer
                        format: int32
                        example: 100
                      resources:
                        description: Resources the Action relates to.
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              description: ID of the Resource.
                              type: integer
                              format: int64
                              minimum: 1
                              maximum: 9007199254740991
                              example: 42
                            type:
                              description: Type of the Resource.
                              type: string
                              example: server
                          required:
                          - id
                          - type
                      error:
                        description: Error message for the Action if an error occurred, otherwise null.
                        type:
                        - object
                        - 'null'
                        properties:
                          code:
                            description: Fixed error code for machines.
                            type: string
                            example: action_failed
                          message:
                            description: Error message for humans.
                            type: string
                            example: Action failed
                        required:
                        - code
                        - message
                    required:
                    - id
                    - command
                    - status
                    - progress
                    - started
                    - finished
                    - resources
                    - error
                required:
                - action
              examples:
                default:
                  value:
                    action:
                      id: 14
                      command: issue_certificate
                      status: success
                      progress: 100
                      started: '2021-01-30T23:55:00Z'
                      finished: '2021-01-30T23:57:00Z'
                      resources:
                      - id: 896
                        type: certificate
                      error:
                        code: action_failed
                        message: Action failed
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
      x-codeSamples:
      - lang: Go
        label: Go
        source: "package examples\n\nimport (\n\t\"context\"\n\t\"os\"\n\n\t\"github.com/hetznercloud/hcloud-go/v2/hcloud\"\n)\n\nfunc main() {\n\ttoken := os.Getenv(\"HCLOUD_TOKEN\")\n\n\tclient := hcloud.NewClient(hcloud.WithToken(token))\n\tctx := context.TODO()\n\n\taction, _, err := client.Certificate.RetryIssuance(ctx, &hcloud.Certificate{ID: 123})\n\n\terr = client.Action.WaitFor(ctx, action)\n}"
      - lang: Python
        label: Python
        source: 'from __future__ import annotations


          from os import environ


          from hcloud import Client

          from hcloud.certificates import Certificate


          token = environ["HCLOUD_TOKEN"]

          client = Client(token=token)


          action = client.certificates.retry_issuance(certificate=Certificate(id=123))


          action.wait_until_finished()'
      - lang: Shell
        label: CLI
        source: hcloud certificate retry $CERTIFICATE
  /certificates/{id}/actions/{action_id}:
    get:
      deprecated: true
      operationId: get_certificate_action
      summary: Get an Action for a Certificate
      description: '**Deprecated**: This operation is deprecated, see our changelog for more details.


        Returns a specific Action for a Certificate. Only type `managed` Certificates have Actions.'
      tags:
      - Certificate Actions
      parameters:
      - description: ID of the Certificate.
        name: id
        in: path
        required: true
        schema:
          description: ID of the [Certificate](#tag/certificates).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      - description: ID of the Action.
        name: action_id
        in: path
        required: true
        schema:
          description: ID of the [Action](#description/actions).
          type: integer
          format: int64
          minimum: 1
          maximum: 9007199254740991
          example: 42
      responses:
        '200':
          description: Request succeeded.
          content:
            application/json:
              schema:
                title: ActionResponse
                type: object
                properties:
                  action:
                    title: Action
                    type: object
                    properties:
                      id:
                        description: ID of the [Action](#description/actions).
                        type: integer
                        format: int64
                        minimum: 1
                        maximum: 9007199254740991
                        example: 42
                      command:
                        description: Command executed in the Action.
                        type: string
                        example: start_resource
                      status:
                        description: Status of the Action.
                        type: string
                        enum:
                        - running
                        - success
                        - error
                      started:
                        description: Point in time when the Action was started (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
                        type: string
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      finished:
                        description: Point in time when the Action was finished (in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format). Only set if the Action is finished otherwise null.
                        type:
                        - string
                        - 'null'
                        format: date-time
                        example: '2016-01-30T23:55:00Z'
                      progress:
                        description: Progress of the Action in percent.
                        type: integer
                        format: int32
                        example: 100
                      resources:
                        description: Resources the Action relates to.
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              description: ID of the Resource.
                              type: integer
                              format: int64
                              minimum: 1
                              maximum: 9007199254740991
                              example: 42
                            type:
                              description: Type of the Resource.
                              type: string
                              example: server
                          required:
                          - id
                          - type
                      error:
                        description: Error message for the Action if an error occurred, otherwise null.
                        type:
                        - object
                        - 'null'
                        properties:
                          code:
                            description: Fixed error code for machines.
                            type: string
                            example: action_failed
                          message:
                            description: Error message for humans.
                            type: string
                            example: Action failed
                        required:
                        - code
                        - message
                    required:
                    - id
                    - command
                    - status
                    - progress
                    - started
                    - finished
                    - resources
                    - error
                required:
                - action
              examples:
                default:
                  value:
                    action:
                      id: 14
                      command: issue_certificate
                      status: success
                      progress: 100
                      started: '2021-01-30T23:55:00Z'
                      finished: '2021-01-30T23:57:00Z'
                      resources:
                      - id: 896
                        type: certificate
                      error:
                        code: action_failed
                        message: Action failed
        4xx:
          description: Request failed with a user error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: unauthorized
                    message: unable to authenticate
                    details: null
        5xx:
          description: Request failed with a server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        description: Error code for machines.
                        type: string
                      message:
                        description: Error message for humans.
                        type: string
                      details:
                        description: Details about the error.
                        type:
                        - object
                        - 'null'
                    required:
                    - code
                    - message
                required:
                - error
                example:
                  error:
                    code: timeout
                    message: request timeout
                    details: null
      security:
      - APIToken: []
components:
  securitySchemes:
    APIToken:
      type: http
      scheme: bearer
x-tagGroups:
- name: Actions
  tags:
  - Actions
- name: Servers
  tags:
  - Servers
  - Server Actions
  - Server Types
  - Images
  - Image Actions
  - ISOs
  - Placement Groups
  - Primary IPs
  - Primary IP Actions
- name: Volumes
  tags:
  - Volumes
  - Volume Actions
- name: Floating IPs
  tags:
  - Floating IPs
  - Floating IP Actions
- name: Firewalls
  tags:
  - Firewalls
  - Firewall Actions
- name: Load Balancers
  tags:
  - Load Balancers
  - Load Balancer Actions
  - Load Balancer Types
- name: Networks
  tags:
  - Networks
  - Network Actions
- name: DNS
  tags:
  - Zones
  - Zone Actions
  - Zone RRSets
  - Zone RRSet Actions
- name: Security
  tags:
  - Certificates
  - Certificate Actions
  - SSH Keys
- name: Locations
  tags:
  - Locations
  - Data Centers
- name: Billing
  tags:
  - Pricing
